// data.js

export const tabsList = [
  "ทั้งหมด",
  "ถุง",
  "ผงปรุงรส",
  "น้ำผลไม้/น้ำหวาน",
  "ของใช้",
  "บรรจุภัณฑ์",
  "ของแห้ง",
  "นม",
  "ท็อปปิ้ง",
  "เครื่องดื่ม",
];

export const initialProducts = [
  // ==========================================
  // หมวด: ผงปรุงรส / เครื่องปรุง
  // ==========================================
  {
    id: 1,
    name: "ผงชูรส อายิโนะโมะโต๊ะ 32 บาท",
    tab: "ผงปรุงรส",
    receiptCategory: "general",
    unit: "ลัง",
    qty: 0,
    image: "/images/อายิ32.webp",
  },
  {
    id: 2,
    name: "ผงชูรส อายิโนะโมะโต๊ะ 1 กก.",
    tab: "ผงปรุงรส",
    receiptCategory: "general",
    unit: "ลัง",
    qty: 0,
    image: "/images/อายิ1กก.jpg", // หมายเหตุ: มีจุดตรง กก. รูปต้องชื่อ "ผงชูรส อายิโนะโมะโต๊ะ 1 กก..jpg" นะครับ
  },
  {
    id: 3,
    name: "ฟ้าไทยถุง สีส้ม",
    tab: "ผงปรุงรส",
    receiptCategory: "general",
    unit: "ลัง",
    qty: 0,
    image: "/images/ฟ้าไทยถุง สีส้ม.jpg",
  },
  {
    id: 4,
    name: "รสดีหมู 450g",
    tab: "ผงปรุงรส",
    receiptCategory: "general",
    unit: "ลัง",
    qty: 0,
    image: "/images/รสดีหมู 450g.png",
  },
  {
    id: 5,
    name: "รสดีหมู 850g",
    tab: "ผงปรุงรส",
    receiptCategory: "general",
    unit: "ลัง",
    qty: 0,
    image: "/images/รสดีหมู 450g.png",
  },
  {
    id: 6,
    name: "ซุปก้อนคนอร์ หมู",
    tab: "ผงปรุงรส",
    receiptCategory: "general",
    unit: "แพ็ค",
    qty: 0,
    image: "/images/ซุปก้อนคนอร์ หมู.jpg",
  },
  {
    id: 7,
    name: "ซุปก้อนคนอร์ ต้มยำ",
    tab: "ผงปรุงรส",
    receiptCategory: "general",
    unit: "แพ็ค",
    qty: 0,
    image: "/images/ซุปก้อนคนอร์ ต้มยำ.jpg",
  },
  {
    id: 8,
    name: "น้ำจิ้มลูกชิ้นจอมยุทธ์",
    tab: "ผงปรุงรส",
    receiptCategory: "general",
    unit: "ลัง",
    qty: 0,
    image: "/images/น้ำจิ้มลูกชิ้นจอมยุทธ์.webp",
  },
  {
    id: 9,
    name: "น้ำจิ้มสุกี้ พันท้าย ขวดใหญ่",
    tab: "ผงปรุงรส",
    receiptCategory: "general",
    unit: "ลัง",
    qty: 0,
    image: "/images/น้ำจิ้มสุกี้ พันท้าย ขวดใหญ่.webp",
  },
  {
    id: 10,
    name: "น้ำจิ้มบ๊วย ตราเด็กสมบูรณ์",
    tab: "ผงปรุงรส",
    receiptCategory: "general",
    unit: "ลัง",
    qty: 0,
    image: "/images/น้ำจิ้มบ๊วย ตราเด็กสมบูรณ์.webp",
  },
  {
    id: 11,
    name: "พริกน้ำปลา ไส้ตัน",
    tab: "ผงปรุงรส",
    receiptCategory: "general",
    unit: "ลัง",
    qty: 0,
    image: "/images/พริกน้ำปลา ไส้ตัน.jpg",
  },
  {
    id: 12,
    name: "น้ำปลา ทิพรส 700 มล.",
    tab: "ผงปรุงรส",
    receiptCategory: "general",
    unit: "ลัง",
    qty: 0,
    image: "/images/น้ำปลา ทิพรส 700 มล..webp",
  },
  {
    id: 13,
    name: "น้ำปลา ทิพรส 280 มล.",
    tab: "ผงปรุงรส",
    receiptCategory: "general",
    unit: "ลัง",
    qty: 0,
    image: "/images/น้ำปลา ทิพรส 280 มล..webp",
  },
  {
    id: 14,
    name: "น้ำปลาติดใจ แกลลอนใหญ่",
    tab: "ผงปรุงรส",
    receiptCategory: "general",
    unit: "แกลลอน",
    qty: 0,
    image: "/images/น้ำปลาติดใจ แกลลอนใหญ่.jpg",
  },
  {
    id: 15,
    name: "น้ำปลาร้า แม่บุญล้ำ ฝาแดง",
    tab: "ผงปรุงรส",
    receiptCategory: "general",
    unit: "แพ็ค",
    qty: 0,
    image: "/images/น้ำปลาร้า แม่บุญล้ำ ฝาแดง.jpg",
  },
  {
    id: 16,
    name: "น้ำมันหอย นกทะเล แกลลอนใหญ่",
    tab: "ผงปรุงรส",
    receiptCategory: "general",
    unit: "แกลลอน",
    qty: 0,
    image: "/images/น้ำมันหอย นกทะเล แกลลอนใหญ่.webp",
  },
  {
    id: 17,
    name: "น้ำมันหอย นกทะเล แกลลอนเล็ก",
    tab: "ผงปรุงรส",
    receiptCategory: "general",
    unit: "แกลลอน",
    qty: 0,
    image: "/images/น้ำมันหอย นกทะเล แกลลอนเล็ก.jpg",
  },
  {
    id: 19,
    name: "น้ำมันหอย ตราแม่ครัว ขวดใหญ่",
    tab: "ผงปรุงรส",
    receiptCategory: "general",
    unit: "ลัง",
    qty: 0,
    image: "/images/น้ำมันหอย ตราแม่ครัว ขวดใหญ่.jpg",
  },
  {
    id: 20,
    name: "ซีอิ๊วขาว ฉลากแดง",
    tab: "ผงปรุงรส",
    receiptCategory: "general",
    unit: "ลัง",
    qty: 0,
    image: "/images/ซีอิ๊วขาว ฉลากแดง.webp",
  },
  {
    id: 21,
    name: "ซีอิ๊วขาว อิคคิว",
    tab: "ผงปรุงรส",
    receiptCategory: "general",
    unit: "ลัง",
    qty: 0,
    image: "/images/ซีอิ๊วขาว อิคคิว.jpg",
  },
  {
    id: 22,
    name: "ซอสฝาเขียว ภูเขาทอง 1000 มล.",
    tab: "ผงปรุงรส",
    receiptCategory: "general",
    unit: "ลัง",
    qty: 0,
    image: "/images/ซอสฝาเขียว ภูเขาทอง 1000 มล..jpg",
  },
  {
    id: 23,
    name: "ซอสปรุงรสฝาส้ม ภูเขาทอง",
    tab: "ผงปรุงรส",
    receiptCategory: "general",
    unit: "ลัง",
    qty: 0,
    image: "/images/ซอสปรุงรสฝาส้ม ภูเขาทอง.png",
  },
  {
    id: 24,
    name: "ซอสปรุงรสฝาน้ำตาล ภูเขาทอง",
    tab: "ผงปรุงรส",
    receiptCategory: "general",
    unit: "ลัง",
    qty: 0,
    image: "/images/ซอสปรุงรสฝาน้ำตาล ภูเขาทอง.jpg",
  },
  {
    id: 25,
    name: "ซอสแม็กกี้ 680 มล.",
    tab: "ผงปรุงรส",
    receiptCategory: "general",
    unit: "ลัง",
    qty: 0,
    image: "/images/ซอสแม็กกี้ 680 มล..webp",
  },
  {
    id: 26,
    name: "ซอสเย็นตาโฟ",
    tab: "ผงปรุงรส",
    receiptCategory: "general",
    unit: "ลัง",
    qty: 0,
    image: "/images/ซอสเย็นตาโฟ.webp",
  },
  {
    id: 27,
    name: "น้ำส้มสายชู ฉลากทอง แกลลอนใหญ่",
    tab: "ผงปรุงรส",
    receiptCategory: "general",
    unit: "แกลลอน",
    qty: 0,
    image: "/images/น้ำส้มสายชู ฉลากทอง แกลลอนใหญ่.jpg",
  },
  {
    id: 28,
    name: "น้ำส้มสายชู อสร ขวดใหญ่",
    tab: "ผงปรุงรส",
    receiptCategory: "general",
    unit: "ลัง",
    qty: 0,
    image: "/images/น้ำส้มสายชู อสร ขวดใหญ่.webp",
  },
  {
    id: 29,
    name: "น้ำส้มสายชู ไร่ทิพย์",
    tab: "ผงปรุงรส",
    receiptCategory: "general",
    unit: "ลัง",
    qty: 0,
    image: "/images/น้ำส้มสายชู ไร่ทิพย์.jpg",
  },
  {
    id: 30,
    name: "น้ำมันตราองุ่น 1 ลิตร",
    tab: "ผงปรุงรส",
    receiptCategory: "general",
    unit: "ลัง",
    qty: 0,
    image: "/images/น้ำมันตราองุ่น 1 ลิตร.jpg",
  },
  {
    id: 31,
    name: "น้ำมันพืชเกสร 1 ลิตร",
    tab: "ผงปรุงรส",
    receiptCategory: "general",
    unit: "ลัง",
    qty: 0,
    image: "/images/น้ำมันพืชเกสร 1 ลิตร.jpg",
  },
  {
    id: 32,
    name: "น้ำมันรินทิพย์ ถุง",
    tab: "ผงปรุงรส",
    receiptCategory: "general",
    unit: "ลัง",
    qty: 0,
    image: "/images/น้ำมันรินทิพย์ ถุง.jpg",
  },
  {
    id: 33,
    name: "น้ำตาลทราย ไร่ทิพย์",
    tab: "ผงปรุงรส",
    receiptCategory: "general",
    unit: "ลัง",
    qty: 0,
    image: "/images/น้ำตาลทราย ไร่ทิพย์.jpg",
  },
  {
    id: 34,
    name: "พริกป่น ไร่ทิพย์",
    tab: "ผงปรุงรส",
    receiptCategory: "general",
    unit: "ลัง",
    qty: 0,
    image: "/images/พริกป่น ไร่ทิพย์.webp",
  },

  // ==========================================
  // หมวด: ของแห้ง
  // ==========================================
  {
    id: 35,
    name: "มาม่าเปลือย",
    tab: "ของแห้ง",
    receiptCategory: "general",
    unit: "ลัง",
    qty: 0,
    image: "/images/มาม่าเปลือย.jpg",
  },
  {
    id: 37,
    name: "แป้งทอดกรอบ ครัววังทิพย์ (ใหญ่)",
    tab: "ของแห้ง",
    receiptCategory: "general",
    unit: "ลัง",
    qty: 0,
    image: "/images/แป้งทอดกรอบ ครัววังทิพย์ (ใหญ่).jpg",
  },
  {
    id: 38,
    name: "แป้งข้าวโพด ครัววังทิพย์",
    tab: "ของแห้ง",
    receiptCategory: "general",
    unit: "ถุง",
    qty: 0,
    image: "/images/แป้งข้าวโพด ครัววังทิพย์.webp",
  },
  {
    id: 39,
    name: "แป้งข้าวเจ้า สามเศียรใหญ่",
    tab: "ของแห้ง",
    receiptCategory: "general",
    unit: "ลัง",
    qty: 0,
    image: "/images/แป้งข้าวเจ้า สามเศียรใหญ่.jpg",
  },
  {
    id: 40,
    name: "แป้งข้าวเจ้า สิงห์ดาว ใหญ่",
    tab: "ของแห้ง",
    receiptCategory: "general",
    unit: "ลัง",
    qty: 0,
    image: "/images/แป้งข้าวเจ้า สิงห์ดาว ใหญ่.jpg",
  },
  {
    id: 41,
    name: "แป้งมัน",
    tab: "ของแห้ง",
    receiptCategory: "general",
    unit: "ถุง",
    qty: 0,
    image: "/images/แป้งมัน.jpg",
  },
  {
    id: 42,
    name: "ถั่วบด ไร่ทิพย์",
    tab: "ของแห้ง",
    receiptCategory: "general",
    unit: "ลัง/มัด",
    qty: 0,
    image: "/images/ถั่วบด ไร่ทิพย์.jpg",
  },
  {
    id: 43,
    name: "กะทิ อร่อยดี ขวดใหญ่",
    tab: "ของแห้ง",
    receiptCategory: "general",
    unit: "ลัง",
    qty: 0,
    image: "/images/กะทิ อร่อยดี ขวดใหญ่.webp",
  },

  // ==========================================
  // หมวด: นม และ เครื่องดื่ม
  // ==========================================
  {
    id: 44,
    name: "เนยแซมซันใหญ่",
    tab: "นม",
    receiptCategory: "general",
    unit: "ลัง",
    qty: 0,
    image: "/images/เนยแซมซันใหญ่.jpg",
  },
  {
    id: 45,
    name: "นมข้นหวาน คาเนชั่น ถุง 2 โล",
    tab: "นม",
    receiptCategory: "general",
    unit: "ลัง",
    qty: 0,
    image: "/images/นมข้นหวาน คาเนชั่น ถุง 2 โล.jpg",
  },
  {
    id: 46,
    name: "นมข้นหวาน ทีพอท ถุง 2 โล",
    tab: "นม",
    receiptCategory: "general",
    unit: "ถุง",
    qty: 0,
    image: "/images/นมข้นหวาน ทีพอท ถุง 2 โล.webp",
  },
  {
    id: 47,
    name: "นมสด กู๊ดวิล กล่อง",
    tab: "นม",
    receiptCategory: "general",
    unit: "ลัง",
    qty: 0,
    image: "/images/นมสด กู๊ด วิล กล่อง.jpg",
  },
  {
    id: 49,
    name: "นมสด ทีพอท กล่อง",
    tab: "นม",
    receiptCategory: "general",
    unit: "ลัง",
    qty: 0,
    image: "/images/นมสด ทีพอท กล่อง.webp",
  },
  {
    id: 50,
    name: "เนสกาแฟกล่อง คู่ 5",
    tab: "เครื่องดื่ม",
    receiptCategory: "general",
    unit: "กล่อง",
    qty: 0,
    image: "/images/เนสกาแฟกล่อง คู่ 5.jpg",
  },

  // ==========================================
  // หมวด: ของใช้
  // ==========================================
  {
    id: 51,
    name: "ตะเกียบ",
    tab: "ของใช้",
    receiptCategory: "general",
    unit: "ลัง",
    qty: 0,
    image: "/images/ตะเกียบ.jpg",
  },
  {
    id: 52,
    name: "กระดาษโรตี 8x8",
    tab: "ของใช้",
    receiptCategory: "general",
    unit: "มัด",
    qty: 0,
    image: "/images/กระดาษโรตี 8x8.jpg",
  },
  {
    id: 53,
    name: "กระดาษ 4x4",
    tab: "ของใช้",
    receiptCategory: "general",
    unit: "ลัง",
    qty: 0,
    image: "/images/กระดาษ 4x4.jpg",
  },
  {
    id: 54,
    name: "กระดาษทิชชู่ตัด สีชมพู",
    tab: "ของใช้",
    receiptCategory: "general",
    unit: "ลัง",
    qty: 0,
    image: "/images/กระดาษทิชชู่ตัด สีชมพู.jpg",
  },
  {
    id: 55,
    name: "หนังยางวงใหญ่",
    tab: "ของใช้",
    receiptCategory: "general",
    unit: "มัด",
    qty: 0,
    image: "/images/หนังยางวงใหญ่.jpg",
  },
  {
    id: 56,
    name: "ไม้เสียบลูกชิ้น เบอร์ 6",
    tab: "ของใช้",
    receiptCategory: "general",
    unit: "ลัง",
    qty: 0,
    image: "/images/ไม้เสียบลูกชิ้น เบอร์ 6.jpg",
  },
  {
    id: 57,
    name: "ช้อนไอศกรีม",
    tab: "ของใช้",
    receiptCategory: "general",
    unit: "หิ้ว/มัด",
    qty: 0,
    image: "/images/ช้อนไอศกรีม.jpg",
  },
  {
    id: 58,
    name: "ซันไลต์ แกลลอนใหญ่",
    tab: "ของใช้",
    receiptCategory: "general",
    unit: "แกลลอน",
    qty: 0,
    image: "/images/ซันไลต์ แกลลอนใหญ่.jpg",
  },
  {
    id: 59,
    name: "ไลปอนเอฟ แกลลอนขาว",
    tab: "ของใช้",
    receiptCategory: "general",
    unit: "ลัง",
    qty: 0,
    image: "/images/ไลปอนเอฟ แกลลอนขาว.jpg",
  },
  {
    id: 60,
    name: "ไลปอนเอฟ แกลลอนใหญ่ (มะกรูด)",
    tab: "ของใช้",
    receiptCategory: "general",
    unit: "ลัง",
    qty: 0,
    image: "/images/ไลปอนเอฟ แกลลอนใหญ่ (มะกรูด).webp",
  },

  // ==========================================
  // หมวด: น้ำผลไม้/น้ำหวาน
  // ==========================================
  {
    id: 61,
    name: "น้ำหวานฮอนบอย สละ",
    tab: "น้ำผลไม้/น้ำหวาน",
    receiptCategory: "general",
    unit: "ลัง",
    qty: 0,
    image: "/images/น้ำหวานฮอนบอย สละ.jpg",
  },
  {
    id: 62,
    name: "น้ำหวานฮอนบอย ส้ม",
    tab: "น้ำผลไม้/น้ำหวาน",
    receiptCategory: "general",
    unit: "ลัง",
    qty: 0,
    image: "/images/น้ำหวานฮอนบอย ส้ม.jpg",
  },
  {
    id: 63,
    name: "น้ำหวานฮอนบอย สับปะรด",
    tab: "น้ำผลไม้/น้ำหวาน",
    receiptCategory: "general",
    unit: "ลัง",
    qty: 0,
    image: "/images/น้ำหวานฮอนบอย สับปะรด.jpg",
  },
  {
    id: 64,
    name: "น้ำหวานฮอนบอย บลูฮาวาย",
    tab: "น้ำผลไม้/น้ำหวาน",
    receiptCategory: "general",
    unit: "ลัง",
    qty: 0,
    image: "/images/น้ำหวานฮอนบอย บลูฮาวาย.jpg",
  },
  {
    id: 65,
    name: "ติ่งฟง น้ำส้ม",
    tab: "น้ำผลไม้/น้ำหวาน",
    receiptCategory: "general",
    unit: "ลัง",
    qty: 0,
    image: "/images/ติ่งฟง น้ำส้ม.png",
  },
  {
    id: 66,
    name: "ติ่งฟง ลิ้นจี่",
    tab: "น้ำผลไม้/น้ำหวาน",
    receiptCategory: "general",
    unit: "ลัง",
    qty: 0,
    image: "/images/ติ่งฟง ลิ้นจี่.png",
  },
  {
    id: 67,
    name: "ติ่งฟง สตรอเบอร์รี่",
    tab: "น้ำผลไม้/น้ำหวาน",
    receiptCategory: "general",
    unit: "ลัง",
    qty: 0,
    image: "/images/ติ่งฟง สตรอเบอร์รี่.webp",
  },

  // ==========================================
  // หมวด: ท็อปปิ้ง
  // ==========================================
  {
    id: 68,
    name: "บุกใบไม้",
    tab: "ท็อปปิ้ง",
    receiptCategory: "general",
    unit: "ลัง",
    qty: 0,
    image: "/images/บุกใบไม้.jpg",
  },
  {
    id: 69,
    name: "วุ้นสลัด",
    tab: "ท็อปปิ้ง",
    receiptCategory: "general",
    unit: "ลัง",
    qty: 0,
    image: "/images/วุ้นสลัด.webp",
  },
  {
    id: 70,
    name: "ลูกชิด",
    tab: "ท็อปปิ้ง",
    receiptCategory: "general",
    unit: "ปี๊บ",
    qty: 0,
    image: "/images/ลูกชิด.webp",
  },
  {
    id: 71,
    name: "วุ้นมะพร้าวแดง",
    tab: "ท็อปปิ้ง",
    receiptCategory: "general",
    unit: "ลัง",
    qty: 0,
    image: "/images/วุ้นมะพร้าวแดง.jpg",
  },
  {
    id: 72,
    name: "วุ้นมะพร้าวขาว",
    tab: "ท็อปปิ้ง",
    receiptCategory: "general",
    unit: "ลัง",
    qty: 0,
    image: "/images/วุ้นมะพร้าวขาว.webp",
  },
  {
    id: 73,
    name: "วุ้นมะพร้าวเขียว",
    tab: "ท็อปปิ้ง",
    receiptCategory: "general",
    unit: "ลัง",
    qty: 0,
    image: "/images/วุ้นมะพร้าวเขียว.jpg",
  },
  {
    id: 74,
    name: "เฉาก๊วย",
    tab: "ท็อปปิ้ง",
    receiptCategory: "general",
    unit: "ลัง",
    qty: 0,
    image: "/images/เฉาก๊วย.jpg",
  },

  // ==========================================
  // หมวด: บรรจุภัณฑ์
  // ==========================================
  {
    id: 75,
    name: "แก้ว 22 ออนซ์ใส",
    tab: "บรรจุภัณฑ์",
    receiptCategory: "general",
    unit: "ลัง",
    qty: 0,
    image: "/images/แก้ว 22 ออนซ์ใส.jpg",
  },
  {
    id: 76,
    name: "กล่องกลมใส 52",
    tab: "บรรจุภัณฑ์",
    receiptCategory: "general",
    unit: "ลัง",
    qty: 0,
    image: "/images/กล่องกลมใส 52.jpg",
  },
  {
    id: 77,
    name: "กล่องใส 104 ไม่ล็อค",
    tab: "บรรจุภัณฑ์",
    receiptCategory: "general",
    unit: "ลัง",
    qty: 0,
    image: "/images/กล่องใส 104 ไม่ล็อค.jpg",
  },
  {
    id: 78,
    name: "กล่องโฟม 501",
    tab: "บรรจุภัณฑ์",
    receiptCategory: "general",
    unit: "ลูก/ลัง",
    qty: 0,
    image: "/images/กล่องโฟม 501.jpg",
  },
  {
    id: 79,
    name: "กล่องโฟม 303",
    tab: "บรรจุภัณฑ์",
    receiptCategory: "general",
    unit: "ลัง",
    qty: 0,
    image: "/images/กล่องโฟม 303.jpg",
  },
  {
    id: 80,
    name: "ชามโฟม 45",
    tab: "บรรจุภัณฑ์",
    receiptCategory: "general",
    unit: "ลัง",
    qty: 0,
    image: "/images/ชามโฟมพลาสติก 45.jpg",
  },

  // ==========================================
  // หมวด: ถุง (แยก Receipt Category ตอนพิมพ์)
  // ==========================================

  // ถุงเงือก
  {
    id: 86,
    name: "ถุงเงือก 6x14",
    tab: "ถุง",
    receiptCategory: "ถุงเงือก",
    unit: "มัด",
    qty: 0,
    image: "/images/ถุงเงือก 6x14.jpg",
  },
  {
    id: 87,
    name: "ถุงเงือก 8x15",
    tab: "ถุง",
    receiptCategory: "ถุงเงือก",
    unit: "มัด",
    qty: 0,
    image: "/images/ถุงเงือก 8x15.jpg",
  },
  {
    id: 88,
    name: "ถุงเงือก 9x18",
    tab: "ถุง",
    receiptCategory: "ถุงเงือก",
    unit: "มัด",
    qty: 0,
    image: "/images/ถุงเงือก 9x18.jpg",
  },

  // ถุงดาว (รวมถุงดาวส้มเข้ามาด้วยแล้ว)
  {
    id: 89,
    name: "ถุงดาว 6x14",
    tab: "ถุง",
    receiptCategory: "ถุงดาว",
    unit: "มัด",
    qty: 0,
    image: "/images/ถุงดาว 6x14.jpg",
  },
  {
    id: 90,
    name: "ถุงดาว 7x15",
    tab: "ถุง",
    receiptCategory: "ถุงดาว",
    unit: "มัด",
    qty: 0,
    image: "/images/ถุงดาว 7x15.jpg",
  },
  {
    id: 91,
    name: "ถุงดาว 8x16",
    tab: "ถุง",
    receiptCategory: "ถุงดาว",
    unit: "มัด",
    qty: 0,
    image: "/images/ถุงดาว 8x16.jpg",
  },
  {
    id: 92,
    name: "ถุงดาว 9x18",
    tab: "ถุง",
    receiptCategory: "ถุงดาว",
    unit: "มัด",
    qty: 0,
    image: "/images/ถุงดาว 9x18.jpg",
  },
  {
    id: 93,
    name: "ถุงดาว 12x20",
    tab: "ถุง",
    receiptCategory: "ถุงดาว",
    unit: "มัด",
    qty: 0,
    image: "/images/ถุงดาว 12x20.webp",
  },
  {
    id: 94,
    name: "ถุงดาว 12x26",
    tab: "ถุง",
    receiptCategory: "ถุงดาว",
    unit: "มัด",
    qty: 0,
    image: "/images/ถุงดาว 12x26.jpg",
  },

  // ถุงร้อน
  {
    id: 97,
    name: "ถุงร้อน 3x5",
    tab: "ถุง",
    receiptCategory: "ถุงร้อน",
    unit: "หิ้ว",
    qty: 0,
    image: "/images/ถุงร้อน 3x5.png",
  },
  {
    id: 98,
    name: "ถุงร้อน 4.5x7",
    tab: "ถุง",
    receiptCategory: "ถุงร้อน",
    unit: "มัด",
    qty: 0,
    image: "/images/ถุงร้อน 4.5x7.jpg",
  },
  {
    id: 99,
    name: "ถุงร้อน 5x8",
    tab: "ถุง",
    receiptCategory: "ถุงร้อน",
    unit: "มัด",
    qty: 0,
    image: "/images/ถุงร้อน 5x8.png",
  },
  {
    id: 100,
    name: "ถุงร้อน 5x10",
    tab: "ถุง",
    receiptCategory: "ถุงร้อน",
    unit: "หิ้ว",
    qty: 0,
    image: "/images/ถุงร้อน 5x10.png",
  },
  {
    id: 101,
    name: "ถุงร้อน 6x10",
    tab: "ถุง",
    receiptCategory: "ถุงร้อน",
    unit: "มัด",
    qty: 0,
    image: "/images/ถุงร้อน 6x10.png",
  },
  {
    id: 102,
    name: "ถุงร้อน 7x14",
    tab: "ถุง",
    receiptCategory: "ถุงร้อน",
    unit: "หิ้ว",
    qty: 0,
    image: "/images/ถุงร้อน 7x14.png",
  },

  // ถุงเย็น
  {
    id: 103,
    name: "ถุงเย็น 7x11",
    tab: "ถุง",
    receiptCategory: "ถุงเย็น",
    unit: "หิ้ว",
    qty: 0,
    image: "/images/ถุงเย็น 7x11.jpg",
  },
  {
    id: 104,
    name: "ถุงเย็น 8x12",
    tab: "ถุง",
    receiptCategory: "ถุงเย็น",
    unit: "มัด",
    qty: 0,
    image: "/images/ถุงเย็น 8x12.jpg",
  },
  {
    id: 105,
    name: "ถุงเย็น 12x18",
    tab: "ถุง",
    receiptCategory: "ถุงเย็น",
    unit: "หิ้ว",
    qty: 0,
    image: "/images/ถุงเย็น 12x18.jpg",
  },

  // ถุงไฮโซ
  {
    id: 106,
    name: "ถุงไฮโซ 6x14",
    tab: "ถุง",
    receiptCategory: "ถุงไฮโซ",
    unit: "มัด/หิ้ว",
    qty: 0,
    image: "/images/ถุงไฮโซ 6x14.jpg",
  },
  {
    id: 107,
    name: "ถุงไฮโซ 8x16",
    tab: "ถุง",
    receiptCategory: "ถุงไฮโซ",
    unit: "มัด",
    qty: 0,
    image: "/images/ถุงไฮโซ 8x16.jpg",
  },

  // ถุงดำ
  {
    id: 108,
    name: "ถุงดำ 24x28",
    tab: "ถุง",
    receiptCategory: "ถุงดำ",
    unit: "แพ็ค",
    qty: 0,
    image: "/images/ถุงดำ 24x28.jpg",
  },
  {
    id: 109,
    name: "ถุงดำ 30x40",
    tab: "ถุง",
    receiptCategory: "ถุงดำ",
    unit: "แพ็ค",
    qty: 0,
    image: "/images/ถุงดำ 30x40.jpg",
  },
];
